// =============================================================================
// Codex Arcade launcher
//
// One Node process that serves the arcade picker and each game from its own
// origin (port). Games keep their absolute asset paths and run exactly as they
// do standalone; the picker embeds them in an iframe and listens for an
// "exit to arcade" postMessage to return to the menu.
//
//   node server.mjs            # serve + open the browser
//   PORT=4000 node server.mjs  # override the arcade port (games take +1, +2…)
//   NO_OPEN=1 node server.mjs  # don't auto-open a browser
// =============================================================================

import http from 'node:http';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import { ARCADE_PORT, GAMES as GAME_DEFS, gamePort, gameDist } from './arcade.config.mjs';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const HOST = process.env.HOST || '127.0.0.1';
const IS_VERCEL = Boolean(process.env.VERCEL);

// Resolve the shared config into concrete ports + dist paths.
const GAMES = GAME_DEFS.map((g) => ({
  id: g.id,
  title: g.title,
  port: gamePort(g),
  dist: gameDist(g),
  path: `/games/${g.id}/`,
}));

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.map': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.ico': 'image/x-icon',
  '.wav': 'audio/wav',
  '.mp3': 'audio/mpeg',
  '.ogg': 'audio/ogg',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.wasm': 'application/wasm',
  '.txt': 'text/plain; charset=utf-8',
};

function send(res, status, body, headers = {}) {
  res.writeHead(status, { 'Cache-Control': 'no-cache', ...headers });
  res.end(body);
}

/** Resolve a URL path to a file inside `rootDir`, blocking traversal. */
function resolveSafe(rootDir, urlPath) {
  let pathname;
  try {
    pathname = decodeURIComponent(new URL(urlPath, 'http://x').pathname);
  } catch {
    return null;
  }
  if (pathname.endsWith('/')) pathname += 'index.html';
  if (pathname === '/') pathname = '/index.html';
  const filePath = path.normalize(path.join(rootDir, pathname));
  if (filePath !== rootDir && !filePath.startsWith(rootDir + path.sep)) return null;
  return filePath;
}

async function serveFile(res, filePath, fallbackIndex = true) {
  try {
    let stat = await fs.stat(filePath);
    if (stat.isDirectory()) {
      if (!fallbackIndex) throw new Error('dir');
      filePath = path.join(filePath, 'index.html');
      stat = await fs.stat(filePath);
    }
    const data = await fs.readFile(filePath);
    send(res, 200, data, {
      'Content-Type': MIME[path.extname(filePath).toLowerCase()] || 'application/octet-stream',
      'Content-Length': stat.size,
    });
  } catch {
    send(res, 404, 'Not found', { 'Content-Type': 'text/plain' });
  }
}

// --- Arcade server (picker) -------------------------------------------------
function runtimeJs() {
  const payload = IS_VERCEL
    ? { games: GAMES.map(({ id, title, path }) => ({ id, title, path })) }
    : {
        // Pin game origins to the bound host so the iframe always reaches the server
        // (avoids localhost-vs-127.0.0.1 / IPv6 resolution mismatches).
        host: HOST,
        protocol: 'http:',
        games: GAMES.map(({ id, title, port }) => ({ id, title, port })),
      };
  return `/* generated by server.mjs */\nwindow.__ARCADE__ = ${JSON.stringify(payload)};\n`;
}

const arcadeServer = http.createServer((req, res) => {
  const urlPath = (req.url || '/').split('?')[0];

  if (urlPath === '/arcade/runtime.js') {
    return send(res, 200, runtimeJs(), { 'Content-Type': MIME['.js'] });
  }
  // Only expose the picker entry + its /arcade assets — never the game source trees.
  if (urlPath === '/' || urlPath === '/index.html') {
    return serveFile(res, path.join(ROOT, 'index.html'), false);
  }
  if (urlPath === '/favicon.ico') {
    return serveFile(res, path.join(ROOT, 'arcade/assets/favicon.svg'), false);
  }
  if (urlPath.startsWith('/arcade/')) {
    const filePath = resolveSafe(ROOT, urlPath);
    if (!filePath) return send(res, 403, 'Forbidden', { 'Content-Type': 'text/plain' });
    return serveFile(res, filePath, false);
  }
  if (IS_VERCEL && urlPath.startsWith('/games/')) {
    const game = GAMES.find((g) => urlPath === g.path.slice(0, -1) || urlPath.startsWith(g.path));
    if (!game) return send(res, 404, 'Not found', { 'Content-Type': 'text/plain' });

    const relativePath = urlPath.slice(game.path.length - 1) || '/';
    const filePath = resolveSafe(path.join(ROOT, 'vercel-static', 'games', game.id), relativePath);
    if (!filePath) return send(res, 403, 'Forbidden', { 'Content-Type': 'text/plain' });
    return serveFile(res, filePath, true);
  }
  return send(res, 404, 'Not found', { 'Content-Type': 'text/plain' });
});

// --- Game servers -----------------------------------------------------------
function makeGameServer(distAbs) {
  return http.createServer((req, res) => {
    const urlPath = (req.url || '/').split('?')[0];
    const filePath = resolveSafe(distAbs, urlPath);
    if (!filePath) return send(res, 403, 'Forbidden', { 'Content-Type': 'text/plain' });
    serveFile(res, filePath, true);
  });
}

// --- Boot --------------------------------------------------------------------
function listen(server, port, label) {
  return new Promise((resolve) => {
    server.once('error', (err) => {
      if (err.code === 'EADDRINUSE') {
        console.error(`\n  ✖ Port ${port} (${label}) is already in use.`);
        console.error('    Close whatever is using it, or set PORT to a free base port.\n');
        process.exit(1);
      }
      throw err;
    });
    server.listen(port, HOST, resolve);
  });
}

async function main() {
  // Warn early if a game hasn't been built yet.
  for (const g of GAMES) {
    const distAbs = path.join(ROOT, g.dist);
    try {
      await fs.access(path.join(distAbs, 'index.html'));
    } catch {
      console.error(`\n  ⚠ ${g.title}: missing ${g.dist}/index.html`);
      console.error(`    Build it first:  npm run build\n`);
    }
  }

  await listen(arcadeServer, ARCADE_PORT, 'arcade');
  for (const g of GAMES) {
    await listen(makeGameServer(path.join(ROOT, g.dist)), g.port, g.id);
  }

  const url = `http://${HOST}:${ARCADE_PORT}/`;
  const line = '─'.repeat(46);
  console.log(`\n  ╔${line}╗`);
  console.log(`    🕹  CODEX ARCADE is live`);
  console.log(`  ╚${line}╝`);
  console.log(`     ▸ Arcade   ${url}`);
  for (const g of GAMES) console.log(`     ▸ ${g.title.padEnd(9)} http://${HOST}:${g.port}/`);
  console.log(`\n     Press Ctrl+C to stop.\n`);

  if (!process.env.NO_OPEN) openBrowser(url);
}

function openBrowser(url) {
  const cmd = process.platform === 'darwin' ? 'open' : process.platform === 'win32' ? 'start' : 'xdg-open';
  try {
    spawn(cmd, [url], { stdio: 'ignore', detached: true, shell: process.platform === 'win32' }).unref();
  } catch {
    /* opening the browser is best-effort */
  }
}

process.on('SIGINT', () => {
  console.log('\n  👋 Arcade powering down.\n');
  process.exit(0);
});

main();
