// Build a static Vercel bundle for the Codex Arcade launcher.
//
// The local launcher serves each game on a separate port so the games can keep
// root-relative asset paths. Vercel serves one origin, so this script builds the
// two shipped games, copies them under /games/<id>/, and rewrites root-relative
// runtime URLs to those mounted paths.

import { spawn } from 'node:child_process';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { GAMES } from '../arcade.config.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'vercel-static');

const DEPLOY_PATHS = {
  'mortal-codex': '/games/mortal-codex',
  flamethrow: '/games/flamethrow',
};

function run(cmd, args, cwd) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { cwd, stdio: 'inherit', shell: process.platform === 'win32' });
    child.on('error', reject);
    child.on('close', (code) =>
      code === 0 ? resolve() : reject(new Error(`${cmd} ${args.join(' ')} exited with ${code}`)),
    );
  });
}

async function copyDir(src, dest, options = {}) {
  await fs.cp(src, dest, {
    recursive: true,
    filter: (from) => {
      const rel = path.relative(src, from);
      if (!rel) return true;
      if (rel.split(path.sep).includes('.DS_Store')) return false;
      return !(options.exclude || []).some((excluded) => rel === excluded || rel.startsWith(`${excluded}${path.sep}`));
    },
  });
}

async function rewriteGameUrls(dir, mountPath) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const file = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      await rewriteGameUrls(file, mountPath);
      continue;
    }
    if (!/\.(html|js|css|json)$/i.test(entry.name)) continue;

    const before = await fs.readFile(file, 'utf8');
    const after = before
      .replaceAll('/assets/', `${mountPath}/assets/`)
      .replaceAll('/configs/', `${mountPath}/configs/`)
      .replaceAll('/favicon.svg', `${mountPath}/favicon.svg`);
    if (after !== before) await fs.writeFile(file, after);
  }
}

await run('npm', ['run', 'build:games'], ROOT);

await fs.rm(OUT, { recursive: true, force: true });
await fs.mkdir(OUT, { recursive: true });
await fs.copyFile(path.join(ROOT, 'index.html'), path.join(OUT, 'index.html'));
await copyDir(path.join(ROOT, 'arcade'), path.join(OUT, 'arcade'));

const staticGames = [];
for (const game of GAMES) {
  const mountPath = DEPLOY_PATHS[game.id];
  if (!mountPath) throw new Error(`Missing Vercel mount path for ${game.id}`);

  const dist = path.join(ROOT, game.dir, 'dist');
  const dest = path.join(OUT, mountPath.slice(1));
  await copyDir(dist, dest, { exclude: game.id === 'mortal-codex' ? ['assets/concepts'] : [] });
  await rewriteGameUrls(dest, mountPath);
  staticGames.push({ id: game.id, title: game.title, path: `${mountPath}/` });
}

const runtime = `/* generated by scripts/build-vercel.mjs */\nwindow.__ARCADE__ = ${JSON.stringify({ games: staticGames }, null, 2)};\n`;
await fs.writeFile(path.join(OUT, 'arcade', 'runtime.js'), runtime);

console.log(`\nBuilt Vercel static output at ${path.relative(ROOT, OUT)}\n`);
